name: All Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: apt-get update
      run: sudo apt-get update
    - name: Install GStreamer
      run: >
        sudo apt-get install -y libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev gstreamer1.0-plugins-base 
        gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav 
        libgstrtspserver-1.0-dev libges-1.0-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --all-features --verbose
    - name: Formatting validations
      run: cargo fmt -- --check
    - name: Clippy Validations
      run: cargo clippy --all-targets --all-features

      
